"""add transaction_name and recurring_bills

Revision ID: 115b82820802
Revises: 43cec0e276ab
Create Date: 2026-04-09 16:28:07.084116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '115b82820802'
down_revision = '43cec0e276ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurring_bills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_bills_account_id'), ['account_id'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_name', sa.String(length=120), server_default='Transaction', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('transaction_name')

    with op.batch_alter_table('recurring_bills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_bills_account_id'))

    op.drop_table('recurring_bills')
    # ### end Alembic commands ###
