"""drop global unique constraint on account name

Revision ID: f95bcc39e9f7
Revises: 6a4f5d7b9c21
Create Date: 2026-05-03 11:23:55.424023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f95bcc39e9f7'
down_revision = '6a4f5d7b9c21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == 'sqlite':
        op.execute('PRAGMA foreign_keys=OFF')
        op.execute(
            """
            CREATE TABLE accounts_new (
                id INTEGER NOT NULL,
                name VARCHAR(50) NOT NULL,
                account_type VARCHAR(30) NOT NULL,
                starting_balance NUMERIC(12, 2) NOT NULL,
                current_balance NUMERIC(12, 2) NOT NULL,
                created_at DATETIME NOT NULL,
                user_id INTEGER,
                PRIMARY KEY (id),
                CONSTRAINT uq_accounts_user_id_name UNIQUE (user_id, name),
                CONSTRAINT fk_accounts_user_id_users FOREIGN KEY(user_id) REFERENCES users (id)
            )
            """
        )
        op.execute(
            """
            INSERT INTO accounts_new (
                id, name, account_type, starting_balance, current_balance, created_at, user_id
            )
            SELECT id, name, account_type, starting_balance, current_balance, created_at, user_id
            FROM accounts
            """
        )
        op.execute('DROP TABLE accounts')
        op.execute('ALTER TABLE accounts_new RENAME TO accounts')
        op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
        op.execute('PRAGMA foreign_keys=ON')
        return

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('accounts_name_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == 'sqlite':
        op.execute('PRAGMA foreign_keys=OFF')
        op.execute(
            """
            CREATE TABLE accounts_new (
                id INTEGER NOT NULL,
                name VARCHAR(80) NOT NULL,
                account_type VARCHAR(30) NOT NULL,
                starting_balance NUMERIC(12, 2) NOT NULL,
                current_balance NUMERIC(12, 2) NOT NULL,
                created_at DATETIME NOT NULL,
                user_id INTEGER,
                PRIMARY KEY (id),
                CONSTRAINT accounts_name_key UNIQUE (name),
                CONSTRAINT uq_accounts_user_id_name UNIQUE (user_id, name),
                CONSTRAINT fk_accounts_user_id_users FOREIGN KEY(user_id) REFERENCES users (id)
            )
            """
        )
        op.execute(
            """
            INSERT INTO accounts_new (
                id, name, account_type, starting_balance, current_balance, created_at, user_id
            )
            SELECT id, name, account_type, starting_balance, current_balance, created_at, user_id
            FROM accounts
            """
        )
        op.execute('DROP TABLE accounts')
        op.execute('ALTER TABLE accounts_new RENAME TO accounts')
        op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
        op.execute('PRAGMA foreign_keys=ON')
        return

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('accounts_name_key'), ['name'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
