"""drop global unique constraint on account name

Revision ID: f95bcc39e9f7
Revises: 6a4f5d7b9c21
Create Date: 2026-05-03 11:23:55.424023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f95bcc39e9f7'
down_revision = '6a4f5d7b9c21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('accounts_name_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('accounts_name_key'), ['name'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
